name: Update GitHub Stats
on:
  schedule:
    - cron: "0 8 * * *" # Tous les jours à 8h UTC
  workflow_dispatch: # Permet de le lancer manuellement

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Utilisation du jeton personnel pour inclure les repos privés
          token: ${{ secrets.GH_STATS_TOKEN }}

          # Paramètres de l'image
          user: Kadawatcha
          template: classic
          base: header, repositories, metadata
          base_indepth: yes # affichage des commits 
          plugin_followup: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          # emplacement img 
          filename: assets/github-stats.svg
          
          # Configuration du commit
          config_timezone: Europe/Paris
          committer_gist: ${{ github.repository_owner }}

      # --- ÉTAPE 2 : LANGAGES LES PLUS UTILISÉS ---
      - name: Génération du graphique des langages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_STATS_TOKEN }}
          user: Kadawatcha
          base: "" # On ne répète pas l'avatar ici
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          # On garde tout (HTML et CSS inclus)
          output_action: commit
          filename: assets/top-langs.svg
